export enum ReminderType {
  FEEDING = "Feeding",
  VACCINATION = "Vaccination",
  MEDICATION = "Medication",
  GROOMING = "Grooming",
  CLEANING = "Cleaning",
  CHECKUP = "Vet Checkup",
  WALKING = "Walking",
  TRAINING = "Training",
  BREEDING = "Breeding",
  REPRODUCTION = "Reproduction",
  WEIGHT_CHECK = "Weight / Growth Check",
  WATER_CHANGE = "Water Change",
  HABITAT_MAINTENANCE = "Habitat Maintenance",
  DEWORMING = "Deworming",
  SOCIALIZATION = "Socialization / Play",
  DOCUMENTS = "Documents / Licenses",
  OTHER = "Other",
}
